spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: **********************
    password: **********************
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: **********************
